source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LKPostingQueueManager_Example', :exclusive => true do
  pod "LKPostingQueueManager", :path => "../"
end

target 'LKPostingQueueManager_Tests', :exclusive => true do
  pod "LKPostingQueueManager", :path => "../"

  
end
